export const UPDATE_WIDTH = 'UPDATE_WIDTH';
export const CLOSE_SUBHEADER = 'CLOSE_SUBHEADER';
export const TOGGLE_SUBHEADER = 'TOGGLE_SUBHEADER';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

//new

export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOAD_USERS_SUCCESS = 'VALIDATE_USER_SUCCESS';

export const CREATE_OPTION_SUCCESS = 'CREATE_OPTION_SUCCESS';
export const LOAD_OPTIONS_SUCCESS = 'LOAD_OPTIONS_SUCCESS';
export const UPDATE_OPTION_SUCCESS = 'UPDATE_OPTION_SUCCESS';


