export const CREATE_POLL_START = 'CREATE_POLL_START';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';

export const LOAD_POLLS_START = 'LOAD_POLLS_START';
export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';
export const LOAD_POLLS_FAILURE = 'LOAD_POLLS_FAILURE';

export const DELETE_POLL_START = 'DELETE_POLL_START';
export const DELETE_POLL_SUCCESS = 'DELETE_POLL_SUCCESS';
export const DELETE_POLL_FAILURE = 'DELETE_POLL_FAILURE';

export const UPDATE_OPTION_START = 'UPDATE_OPTION_START';
export const UPDATE_OPTION_SUCCESS = 'UPDATE_OPTION_SUCCESS';
export const UPDATE_OPTION_FAILURE = 'UPDATE_OPTION_FAILURE';
